### ISSUE TITLE
window10x64 environment cannot generate the final onnx2bnn.exe

### ISSUE THREAD

**Issue by Sakulaki** [JDAI-CV/dabnn#12]
1>------ 已启动生成: 项目: ZERO_CHECK, 配置: Release x64 ------
1>Checking Build System
1>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/glog/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/tools/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/tools/onnx2bnn/CMakeFiles/generate.stamp is up-to-date.
2>------ 已启动生成: 项目: gen_onnx_proto, 配置: Release x64 ------
3>------ 已启动生成: 项目: glog, 配置: Release x64 ------
4>------ 已启动生成: 项目: onnxifi_loader, 配置: Release x64 ------
5>------ 已启动生成: 项目: onnxifi_dummy, 配置: Release x64 ------
2>Running gen_proto.py on onnx/onnx.in.proto
4>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/third_party/onnx/CMakeLists.txt
3>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/third_party/glog/CMakeLists.txt
4>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/CMakeFiles/generate.stamp is up-to-date.
3>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/glog/CMakeFiles/generate.stamp is up-to-date.
4>onnxifi_loader.c
3>cl : 命令行 warning D9002: 忽略未知选项“-O3”
3>demangle.cc
2>Processing D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\onnx.in.proto
2>Writing D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx_onnx_bnn.proto
2>Writing D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx_onnx_bnn.proto3
2>Writing D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx.pb.h
2>generating D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx_pb.py
2>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/third_party/onnx/CMakeLists.txt
2>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/CMakeFiles/generate.stamp is up-to-date.
2>Running C++ protocol buffer compiler on D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx/onnx_onnx_bnn.proto
6>------ 已启动生成: 项目: onnx_proto, 配置: Release x64 ------
6>Running gen_proto.py on onnx/onnx-operators.in.proto
3>logging.cc
4>onnxifi_loader.vcxproj -> D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\Release\onnxifi_loader.lib
7>------ 已启动生成: 项目: onnxifi_wrapper, 配置: Release x64 ------
6>Processing D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\onnx-operators.in.proto
6>Writing D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx-operators_onnx_bnn.proto
6>Writing D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx-operators_onnx_bnn.proto3
6>Writing D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx-operators.pb.h
6>generating D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx\onnx_operators_pb.py
6>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/third_party/onnx/CMakeLists.txt
6>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/CMakeFiles/generate.stamp is up-to-date.
6>Running C++ protocol buffer compiler on D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/onnx/onnx-operators_onnx_bnn.proto
5>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/third_party/onnx/CMakeLists.txt
6>cl : 命令行 warning D9002: 忽略未知选项“-O3”
5>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/CMakeFiles/generate.stamp is up-to-date.
6>cl : 命令行 warning D9002: 忽略未知选项“-O3”
6>onnx_onnx_bnn.pb.cc
6>cl : 命令行 warning D9002: 忽略未知选项“-O3”
6>onnx-operators_onnx_bnn.pb.cc
5>onnxifi_dummy.c
5>  正在创建库 D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/Release/onnxifi_dummy.lib 和对象 D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/Release/onnxifi_dummy.exp
3>raw_logging.cc
5>onnxifi_dummy.vcxproj -> D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\Release\onnxifi_dummy.dll
6>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\onnx\onnx_onnx_bnn.pb.cc)
6>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\onnx\onnx_onnx_bnn.pb.cc)
6>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\onnx\onnx-operators_onnx_bnn.pb.cc)
6>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\onnx\onnx-operators_onnx_bnn.pb.cc)
6>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\onnx\onnx_onnx_bnn.pb.cc)
6>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\build\third_party\onnx\onnx\onnx-operators_onnx_bnn.pb.cc)
3>symbolize.cc
6>已完成生成项目“onnx_proto.vcxproj”的操作 - 失败。
8>------ 已启动生成: 项目: onnx, 配置: Release x64 ------
8>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/third_party/onnx/CMakeLists.txt
8>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/third_party/onnx/CMakeFiles/generate.stamp is up-to-date.
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>checker.cc
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>assertions.cc
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>ir_pb_converter.cc
8>interned_strings.cc
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>model_helpers.cc
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>status.cc
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>data_type_utils.cc
8>cl : 命令行 warning D9002: 忽略未知选项“-O3”
8>experiments_functions.cc
8>function.cc
3>utilities.cc
8>schema.cc
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\common\model_helpers.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\common\model_helpers.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\experiments\experiments_functions.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\experiments\experiments_functions.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\common\ir_pb_converter.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\common\ir_pb_converter.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\common\model_helpers.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\experiments\experiments_functions.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\data_type_utils.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\data_type_utils.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\common\ir_pb_converter.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\checker.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\checker.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\data_type_utils.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\checker.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\function.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\function.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\function.cc)
8>onnxifi_utils.cc
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\schema.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\schema.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\defs\schema.cc)
8>optimize.cc
3>vlog_is_on.cc
8>pass.cc
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\onnxifi_utils.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\onnxifi_utils.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\onnxifi_utils.cc)
8>pass_manager.cc
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\optimize.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\optimize.cc)
8>pass_registry.cc
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\optimize.cc)
8>implementation.cc
3>signalhandler.cc
8>convert.cc
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass.cc)
8>helper.cc
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass_manager.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass_manager.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass_manager.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass_registry.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass_registry.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\optimizer\pass_registry.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\shape_inference\implementation.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\shape_inference\implementation.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\shape_inference\implementation.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\version_converter\convert.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\version_converter\convert.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\version_converter\convert.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): error C2220: 警告被视为错误 - 没有生成“object”文件 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\version_converter\helper.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\version_converter\helper.cc)
8>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据 (编译源文件 D:\learningAbout\PycharmProjects\dabnn\third_party\onnx\onnx\version_converter\helper.cc)
3>正在生成代码...
3>cl : 命令行 warning D9002: 忽略未知选项“-O3”
3>port.cc
3>glog.vcxproj -> D:\learningAbout\PycharmProjects\dabnn\build\third_party\glog\Release\glog.lib
3>已完成生成项目“glog.vcxproj”的操作。
8>已完成生成项目“onnx.vcxproj”的操作 - 失败。
9>------ 已启动生成: 项目: onnx2bnn, 配置: Release x64 ------
9>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/tools/onnx2bnn/CMakeLists.txt
9>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/tools/onnx2bnn/CMakeFiles/generate.stamp is up-to-date.
9>cl : 命令行 warning D9002: 忽略未知选项“-O3”
9>onnx2bnn.cpp
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(178): error C2220: 警告被视为错误 - 没有生成“object”文件
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(178): warning C4100: “arena”: 未引用的形参
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(177): warning C4100: “default_value”: 未引用的形参
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(359): warning C4127: 条件表达式是常量
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(359): note: 考虑改用 "if constexpr" 语句
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(366): warning C4127: 条件表达式是常量
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(366): note: 考虑改用 "if constexpr" 语句
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据
9>D:\learningAbout\PycharmProjects\dabnn\common/StrKeyMap.h(29): warning C4101: “e”: 未引用的局部变量
9>D:\learningAbout\PycharmProjects\dabnn\common/StrKeyMap.h(26): note: 编译 类 模板 成员函数 "const V &StrKeyMap<V>::at(const std::string &) const" 时
9>        with
9>        [
9>            V=bnn::Shaper::Shape
9>        ]
9>D:\learningAbout\PycharmProjects\dabnn\common/Shaper.h(102): note: 参见对正在编译的函数 模板 实例化“const V &StrKeyMap<V>::at(const std::string &) const”的引用
9>        with
9>        [
9>            V=bnn::Shaper::Shape
9>        ]
9>D:\learningAbout\PycharmProjects\dabnn\common/Shaper.h(113): note: 参见对正在编译的 类 模板 实例化 "StrKeyMap<bnn::Shaper::Shape>" 的引用
9>OnnxConverter.cpp
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(178): error C2220: 警告被视为错误 - 没有生成“object”文件
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(178): warning C4100: “arena”: 未引用的形参
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(177): warning C4100: “default_value”: 未引用的形参
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(359): warning C4127: 条件表达式是常量
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(359): note: 考虑改用 "if constexpr" 语句
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(366): warning C4127: 条件表达式是常量
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(366): note: 考虑改用 "if constexpr" 语句
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据
9>D:\learningAbout\PycharmProjects\dabnn\common/common_bitpack.h(18): error C2338: bits.to_ulong() must return uint64_t
9>D:\learningAbout\PycharmProjects\dabnn\common/common_bitpack.h(40): error C2338: bits.to_ulong() must return uint64_t
9>NodeAttrHelper.cpp
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(178): error C2220: 警告被视为错误 - 没有生成“object”文件
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(178): warning C4100: “arena”: 未引用的形参
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/arenastring.h(177): warning C4100: “default_value”: 未引用的形参
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(359): warning C4127: 条件表达式是常量
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(359): note: 考虑改用 "if constexpr" 语句
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(366): warning C4127: 条件表达式是常量
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/stubs/strutil.h(366): note: 考虑改用 "if constexpr" 语句
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/wire_format_lite.h(935): warning C4244: “参数”: 从“google::protobuf::uint64”转换到“google::protobuf::uint32”，可能丢失数据
9>C:\protobuf\protobuf-3.7.1\src\google/protobuf/parse_context.h(269): warning C4244: “-=”: 从“google::protobuf::stringpiece_ssize_type”转换到“int”，可能丢失数据
9>Shaper.cpp
9>D:\learningAbout\PycharmProjects\dabnn\common\Shaper.cpp(254): error C2220: 警告被视为错误 - 没有生成“object”文件
9>D:\learningAbout\PycharmProjects\dabnn\common\Shaper.cpp(254): warning C4267: “/=”: 从“size_t”转换到“_Ty”，可能丢失数据
9>        with
9>        [
9>            _Ty=std::seed_seq::result_type
9>        ]
9>D:\learningAbout\PycharmProjects\dabnn\common\StrKeyMap.h(29): warning C4101: “e”: 未引用的局部变量
9>D:\learningAbout\PycharmProjects\dabnn\common\StrKeyMap.h(26): note: 编译 类 模板 成员函数 "const V &StrKeyMap<V>::at(const std::string &) const" 时
9>        with
9>        [
9>            V=bnn::Shaper::Shape
9>        ]
9>D:\learningAbout\PycharmProjects\dabnn\common\Shaper.h(102): note: 参见对正在编译的函数 模板 实例化“const V &StrKeyMap<V>::at(const std::string &) const”的引用
9>        with
9>        [
9>            V=bnn::Shaper::Shape
9>        ]
9>D:\learningAbout\PycharmProjects\dabnn\common\Shaper.h(113): note: 参见对正在编译的 类 模板 实例化 "StrKeyMap<bnn::Shaper::Shape>" 的引用
9>正在生成代码...
9>已完成生成项目“onnx2bnn.vcxproj”的操作 - 失败。
10>------ 已启动生成: 项目: ALL_BUILD, 配置: Release x64 ------
10>Building Custom Rule D:/learningAbout/PycharmProjects/dabnn/CMakeLists.txt
10>CMake does not need to re-run because D:/learningAbout/PycharmProjects/dabnn/build/CMakeFiles/generate.stamp is up-to-date.
========== 生成: 成功 7 个，失败 3 个，最新 0 个，跳过 0 个 ==========

**Comment by daquexian** [comment]
Thanks for your valuable report!

For Linux, macos and Windows users, pre-built onnx2bnn binaries have been published on https://github.com/JDAI-CV/dabnn/releases
