### ISSUE TITLE
When using onnx2bnn, the network channels c should must satisfy c %64 == 0, otherwise, there will be a problem.

### ISSUE THREAD

**Issue by Sakulaki** [JDAI-CV/dabnn#23]
I0517 20:34:54.114783 15334 OnnxConverter.cpp:145] c % 64 == 0 is not satisfied! [48, 3, 3, 48] 
terminate called after throwing an instance of 'std::runtime_error'
  what():  c % 64 == 0 is not satisfied! [48, 3, 3, 48] 
Aborted (core dumped)

**Comment by daquexian** [comment]
Fixed in #49 and #51
