### ISSUE TITLE
Any comparison with Bitstream?

### ISSUE THREAD

**Issue by HolmesShuan** [JDAI-CV/dabnn#44]
Nice job! Bitstream refers to [BitStream: An efficient framework for inference of binary neural networks on CPUs](https://www.sciencedirect.com/science/article/pii/S0167865519301230). Thanks in advance.

**Comment by daquexian** [comment]
Thanks for your issue! I am looking forward to compare with BitStream.
Unfortunately,
BitStream is not open source and even not publicly available. So there is
no way to compare them quantitatively. There is some rough comparison in
our acm mm paper, which will be published soon.

**Comment by daquexian** [comment]
Copied from our acm mm paper:

![image](https://user-images.githubusercontent.com/11607199/62093358-90342900-b2ab-11e9-961a-8748f4967636.png)

We will publish our paper on arxiv soon.

**Comment by daquexian** [comment]
BTW, I benefit a lot from your repos like https://github.com/HolmesShuan/ResNet-18-Caffemodel-on-ImageNet :) Thanks for your contribution.

Would you like to join our QQ group (1021964010, answer: nndab)?

**Comment by HolmesShuan** [comment]
Thanks for your invitation, I'm currently working for another AI company on the deployment of CNN on edge devices. Hope to see your work soon!
