### ISSUE TITLE
It might be  better to change protobuf::libprotobuf to ${Protobuf_LIBRARIES}, becasue protobuf::libprotobuf doesn't work in the lower version of cmake

### ISSUE THREAD

**Issue by DinghaoZhang** [JDAI-CV/dabnn#59]
In ``tools/onnx2bnn/CMakeLists.txt``, it might be  better to change protobuf::libprotobuf to ${Protobuf_LIBRARIES}, becasue protobuf::libprotobuf doesn't work in the lower version of cmake, util cmake 3.9.

**Comment by daquexian** [comment]
Thanks! I'll fix it soon

**Comment by daquexian** [comment]
Fixed in #60, merge after CI passes

**Comment by daquexian** [comment]
BTW, have you joined dabnn QQ group, 1021964010?

**Comment by daquexian** [comment]
#60 is merged, could you please verify it on your side? thanks!

**Comment by DinghaoZhang** [comment]
> #60 is merged, could you please verify it on your side? thanks!

I have changed it. Thank you very much. dabnn is a very useful tool.

**Comment by daquexian** [comment]
> I have changed it. Thank you very much. dabnn is a very useful tool.

Thanks!

**Comment by daquexian** [comment]
> I have changed it. Thank you very much. dabnn is a very useful tool.

Thanks!
